# Regular Expression Concepts in Python DataFrame (Pandas)

### We mainly use regex in Pandas with:

### 1. Basic Pattern Matching
##### `.` → Any character

In [20]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ram', 'Rim', 'Rom', 'Rkm']
})

df[df['Name'].str.contains('R.m')]

# Matches: Ram, Rim, Rom

  Name
0  Ram
1  Rim
2  Rom
3  Rkm

## 2. Starts With `^`

In [7]:
df = pd.DataFrame({'City': ['Delhi', 'Mumbai', 'Dehradun', 'Pune']})

df[df['City'].str.contains('^De')]

# Matches: Delhi, Dehradun

       City
0     Delhi
2  Dehradun

## 3. Ends With `$`

In [12]:
df = pd.DataFrame({'City': ['Delhi', 'Mumbai', 'Dehradun', 'Pune']})

df[df['City'].str.contains('ne$')]

# Matches: Pune

   City
3  Pune

## 4. Digit `\d`

In [13]:
df = pd.DataFrame({'Code': ['A123', 'B456', 'C789', 'ABC']})

df[df['Code'].str.contains('\d')]

#Matches rows containing numbers.

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\user\AppData\Local\Temp\ipykernel_15056\307694453.py:3: SyntaxWarning: invalid escape sequence '\d'
  df[df['Code'].str.contains('\d')]

   Code
0  A123
1  B456
2  C789

## 5. Non-Digit `\D`

In [16]:
df = pd.DataFrame({'Code': ['A123', 'B456', '789', 'ABC']})

df[df['Code'].str.contains('\D')]

<>:3: SyntaxWarning: invalid escape sequence '\D'
<>:3: SyntaxWarning: invalid escape sequence '\D'
C:\Users\user\AppData\Local\Temp\ipykernel_15056\2024733828.py:3: SyntaxWarning: invalid escape sequence '\D'
  df[df['Code'].str.contains('\D')]

   Code
0  A123
1  B456
3   ABC

## 6. Alphabets `[a-z]`

In [18]:
df = pd.DataFrame({'Code': ['A123', 'B456', '789', 'ABC']})

df[df['Code'].str.contains('[A-Z]')]

   Code
0  A123
1  B456
3   ABC

## 7. Multiple Characters `[abc]`

In [22]:
df = pd.DataFrame({
    'Name': ['Ram', 'Rim', 'Rom', 'Rkm']
})

df[df['Name'].str.contains('[aeiou]')]

#Match a OR b OR c

  Name
0  Ram
1  Rim
2  Rom

## 8. Not in List `[^abc]`

In [24]:
df = pd.DataFrame({
    'Name': ['Ram', 'Rim', 'Rom', 'Rkm']
})

df[df['Name'].str.contains('[^aeiou]')]

  Name
0  Ram
1  Rim
2  Rom
3  Rkm

## 9. OR Operator `|`

In [26]:
df = pd.DataFrame({'City': ['Delhi', 'Mumbai', 'Dehradun', 'Pune']})

df[df['City'].str.contains('Delhi|Pune')]

    City
0  Delhi
3   Pune

## 10. Zero or More `*`

In [31]:
df = pd.DataFrame({'Text': ['ab', 'aab', 'aaab', 'b', '21']})

df[df['Text'].str.contains('a*b')]

   Text
0    ab
1   aab
2  aaab
3     b

## 11. One or More `+`

In [32]:
df[df['Text'].str.contains('a+b')]

   Text
0    ab
1   aab
2  aaab

## 12. Optional `?`

In [33]:
df[df['Text'].str.contains('a?b')]

   Text
0    ab
1   aab
2  aaab
3     b

## 13. Exact Number `{n}`

In [35]:
df = pd.DataFrame({'Num': ['123', '1234', '12']})

df[df['Num'].str.contains('\d{3}')]

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\user\AppData\Local\Temp\ipykernel_15056\3890908670.py:3: SyntaxWarning: invalid escape sequence '\d'
  df[df['Num'].str.contains('\d{3}')]

    Num
0   123
1  1234

## 14. Range `{n,m}`

In [37]:
df[df['Num'].str.contains('\d{2,3}')]

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\user\AppData\Local\Temp\ipykernel_15056\2661326514.py:1: SyntaxWarning: invalid escape sequence '\d'
  df[df['Num'].str.contains('\d{2,3}')]

    Num
0   123
1  1234
2    12

# 15. Word Boundary `\b`

In [40]:
df = pd.DataFrame({'Text': ['cat', 'scatter', 'cat dog']})

df[df['Text'].str.contains(r'\bcat\b')]

# Matches exact word "cat".

      Text
0      cat
2  cat dog

## 16. Extract Data using Regex

In [46]:
df = pd.DataFrame({'Email': ['abc@gmail.com', 'xyz@yahoo.com']})

df['Username'] = df['Email'].str.extract(r'(\w+)@')
df

           Email Username
0  abc@gmail.com      abc
1  xyz@yahoo.com      xyz

## 17. Replace using Regex

In [48]:
df = pd.DataFrame({'Email': ['abc@gmail.com', 'xyz@yahoo.com']})

df['Email'] = df['Email'].str.replace(r'@.*', '', regex=True)
df

  Email
0   abc
1   xyz

## 18. Find All Matches

In [52]:
df = pd.DataFrame({'Text': ['abc123', 'def456']})
df['Numbers'] = df['Text'].str.findall('\d+')
df

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\user\AppData\Local\Temp\ipykernel_15056\1265323394.py:2: SyntaxWarning: invalid escape sequence '\d'
  df['Numbers'] = df['Text'].str.findall('\d+')

     Text Numbers
0  abc123   [123]
1  def456   [456]

## 19. Match Pattern from Start

In [54]:
df = pd.DataFrame({'Text': ['abc123', 'def456', "123adc"]})

df[df['Text'].str.match('[a-z]+')]

     Text
0  abc123
1  def456

## Summary Table (Important Regex Symbols)

| Regex	| Meaning |
|----------|-------------|
| `.`	| Any character |	
| `^`	| Start |	
| `$`	| End |
| `\d` |	Digit |	
| `\D` |	Non-digit |	
| `\w` |	Word |	
| `\W` |	Non-word |	
| `\s` |	Space |	
| `\S` |	Non-space |	
| `[]` |	Range |	
| `[^]` |	Not	|
|   | OR |
| `*`	| 0 or more |	
| `+`	| 1 or more |	
| `?`	| Optional |	
| `{n}` |	Exact |	
| `{n,m}` |	Range |	
| `\b` |	Word boundary |